resolver: lts-2.22
packages:
- '.'
extra-deps:
- HDBC-2.4.0.1
- HDBC-session-0.1.0.0
- names-th-0.2.0.1
- persistable-record-0.2.0.0
- relational-query-0.7.1.0
- relational-query-HDBC-0.4.0.0
- relational-schemas-0.1.2.1
- sql-words-0.1.3.1
flags:
  HDBC:
    mintime15: false
extra-package-dbs: []
